server:
  port: 8085
  servlet:
    context-path: /api/account
management:
  server:
    port: 8185
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  liquibase:
    default-schema: account
    change-log: db.changelog/db.changelog-master.yaml
    enabled: ${LIQUIBASE_ENABLED:true}
    drop-first: ${LIQUIBASE_DROP_FIRST:false}
  application:
    name: account-app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id:
          new_generator_mappings: false
          hibernate.default_schema: account
springdoc:
  api-docs:
    path: /
  swagger-ui:
    url: /
    path: /swagger-ui.html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: account-app