server:
  port: 8091
  servlet:
    context-path: /api/public-info
management:
  server:
    port: 8190
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
  liquibase:
    default-schema: public_bank_information
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public_bank_information
  application:
    name: public-info-app
springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        url: /v3/api-docs
        path: /swagger-ui/

