---
server:
  port: 8092
  servlet:
    context-path: /api/transfer
management:
  server:
    port: 8191
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    default-schema: transfer
    change-log: db/changelog/db.changelog-master.yaml
    enabled: false
    drop-first: false
  application:
    name: transfer-app
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
