global:
  scrape_interval: 5s
  external_labels: 'codelab-monitor'

scrape_configs:
  - job_name: 'anti-fraud-app'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8585']
