version: '3.7'

x-environment: &app_environment
  SPRING_DATASOURCE_URL: jdbc:postgresql://bank-db:5432/postgres
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

services:
  bank-db:
    image: postgres
    hostname: bank-db
    ports:
      - "5433:5432"
    networks:
      - bank-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build: ../eureka-service/
    hostname: eureka-server
    ports:
      - "8762:8761"
    networks:
      - bank-network
    depends_on:
      - bank-db

  anti-fraud-app:
    build: ../antifraud/
    hostname: anti-fraud-app
    ports:
      - "8087:8086"
      - "8187:8186"
    networks:
      - bank-network
    environment:
      <<: *app_environment
    depends_on:
      bank-db:
        condition: service_healthy
      eureka-server:
        condition: service_started

  transfer-app:
    build: ../transfer/
    hostname: transfer-app
    ports:
      - "8093:8092"
      - "8193:8192"
    environment:
      <<: *app_environment
    networks:
      - bank-network
    depends_on:
      bank-db:
        condition: service_healthy
      eureka-server:
        condition: service_started

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bank-network
    depends_on:
      anti-fraud-app:
        condition: service_started
      transfer-app:
        condition: service_started

  grafana:
    build: ./grafana/
    hostname: grafana
    ports:
    - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - bank-network

networks:
  bank-network:
    name: bank-network
    driver: bridge
