global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'bank_services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'anti-fraud-app:8186'
          - 'transfer-app:8191'