services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yml
    restart: always